Functionality for Xi_rppi from Pk
abacusorg/abacusutils pull request #115
Opened 2023-10-03 00:09 UTC by boryanah

2023-10-09 17:45 UTC, lgarrison requested changes
Just a few comments, looks fine overall!

2023-10-09 17:45 UTC, lgarrison commented on abacusnbody/analysis/power_spectrum.py
> +def calc_field(pos,
This function kind of just seems like a `for` loop over two position arrays, calling `get_field_fft()` on each. The only difference I see is that `W` is only calculated once; is it really worth having a function just for that? Could the `W` calculation be an option of `get_field_fft()` instead, removing the need for this function?

I don't see any reason why `get_field_fft()` couldn't be updated to accept multiple arrays, too. I think a good API there would be to return the same number of arrays as given in the `pos` argument, instead of explicit `pos` and `pos2` args.

2023-10-09 17:45 UTC, lgarrison commented on abacusnbody/metadata/abacussummit.py
> +        simname = 'Abacus' + simname
Let's leave this as `if not simname.startswith('AbacusSummit_'):`. The reason is so that someone can type `get_meta("base_c000_ph000")` as a shorthand. I don't think it's critical to support all prefixes here; this module is called `AbacusSummit` after all!

2023-10-09 17:45 UTC, lgarrison commented on abacusnbody/metadata/abacussummit.py
> +        for i, metadata_fn in enumerate(metadata_fns):
Any reason to `enumerate` here?

2023-10-09 17:45 UTC, lgarrison commented on abacusnbody/analysis/power_spectrum.py
> +    space : str
There will probably only ever be two options for this, right? So it could just be a bool called something like 'fourier`?

2023-10-09 17:45 UTC, lgarrison commented on abacusnbody/analysis/power_spectrum.py
> +        number of modes per (kp, pi) bin.
Thinking about the API, for many applications (e.g. MCMC or optimization) one wants to compute the counts once but the weighted counts many times (since the counts are static for a given geometry). The current API forces you to count both every time, so it's slower. (Not sure how much slower though; you could comment out the `counts` update and benchmark it.)

2023-10-09 17:45 UTC, lgarrison commented on abacusnbody/analysis/power_spectrum.py
> +def bin_kppi(n1d, L, kedges, pimax, Npi, weights, dtype=np.float32,
Are you pretty sure that we'll only ever need linear pi bins?

2023-10-18 19:01 UTC, boryanah commented on abacusnbody/metadata/abacussummit.py
> +        for i, metadata_fn in enumerate(metadata_fns):
Not sure I understand but is the idea that enumerate is slower or wordier? Changed to `range(len(metadata_fns))`

2023-10-18 19:11 UTC, boryanah commented on abacusnbody/analysis/power_spectrum.py
> +    space : str
Changed to `fourier`:)

2023-10-18 19:13 UTC, boryanah commented on abacusnbody/analysis/power_spectrum.py
> +def bin_kppi(n1d, L, kedges, pimax, Npi, weights, dtype=np.float32,
I haven't seen an application where one uses anything else, and I thought it was the default behavior in most correlation function codes (including `Corrfunc`)..

2023-10-18 20:11 UTC, boryanah commented on abacusnbody/analysis/power_spectrum.py
> +def calc_field(pos,
So if we only keep `get_field_fft()`, then I have two questions (I think I have the first one regardless):
1) how should we pass the multiple `pos` arrays? Are you suggesting that the user can pass a list of position arrays? I suspect you mean something else -- if there is a cleverer way of doing this, can you show? I will push the other changes.
2) for making the `W` change, would it be the case that `W` is by default None, but if `compensated = True`, then you can update to the correct thing. Then what is unclear to me is that I think that would only change `W` locally... I think not, which would be nice, though I should check. Is this what you had in mind?

2023-10-19 14:35 UTC, lgarrison commented on abacusnbody/analysis/power_spectrum.py
> +def calc_field(pos,
1. One way would be to allow the user to pass either a plain pos array or a list/tuple of pos arrays. Then the function returns the same type that was passed. From the user side, that would look like:
```python
posfft = get_field_fft(pos, ...)
pos1fft, pos2fft = get_field_fft((pos1,pos2), ...)
```

2. I think that would be fine; `W = None` can mean "auto", `W = False` can mean "no window", and `W = <array>` can be a custom window (but is that ever needed?). In the case of auto, the logic can just be what already exists in `calc_field()`.

2023-10-19 14:37 UTC, lgarrison commented on abacusnbody/metadata/abacussummit.py
> +        simname = 'Abacus' + simname
Oh, yes, good point. Maybe we just remove this logic then, it's probably getting unnecessarily complex...

2023-10-19 14:49 UTC, lgarrison commented on abacusnbody/analysis/power_spectrum.py
> +        number of modes per (kp, pi) bin.
Probably not then, thanks for checking.

2023-11-07 14:50 UTC, lgarrison commented
We should probably do a release soon, do you want to try to finish this PR before then?

2023-11-12 01:02 UTC, boryanah commented on abacusnbody/analysis/power_spectrum.py
> +def calc_field(pos,
Sorry for the big delay -- I've been ruminating on this for a while, and I decided to go back to the original version without `calc_field`. `W` was actually already computed only once and passed to `get_field_fft`, so we wouldn't be gaining anything or changing things much. I also am not sure I find passing either pos array or list of pos arrays an intuitive option either. I think that in the case of a power spectrum, it is more satisfying/less confusing to think of first and second field that are being cross-correlated than an open-ended number of arrays.

2023-11-12 03:18 UTC, lgarrison commented on abacusnbody/analysis/power_spectrum.py
> +def calc_field(pos,
Sounds good, thanks!

2023-11-12 03:30 UTC, lgarrison commented
A few small things:
- `pk_to_xi()` takes a filename as an argument, rather than a power spectrum. Not sure I follow why, can't a user just open the file and pass the contents to the function?
- The functions like `bin_kmu()` now return 5 values after adding kavg; this seems like a lot, maybe we should be returning a dict now instead? It would have to be a Numba typed dict, but I think that's okay. It's just really verbose to have to unpack 5 return values every time you use that function.

And a question: I tried to make `calc_power()` return a user-friendly Astropy Table, but I can't decide if the columns and shapes actually ended up being user-friendly... the `'power'` column has shape `(N_k, N_poles)`, for example, but maybe the multipoles should just be different columns. Have you played around with this function/any thoughts of how we should structure the outputs?

2023-11-12 22:27 UTC, boryanah commented
The reason that `pk_to_xi` takes a file name is because I found this to be saving important cpu power when running CV, which if I instead empty the file content runs out of memory on a single node (because I can't delete the file content while the function is being called). Perhaps, the better thing to do is to allow the user to either pass an array or a file name and interpret it appropriately like what I am currently doing in `shear.py`
```
    # user can also pass string
    if isinstance(dsmo, str):
        dsmo = np.load(dsmo)
```
If you think that's a good idea, I am happy to make that the case. To me, that is preferable so that CV can run with nmesh = 1152 on a single node. Speaking of `shear.py`, it's an old code I wrote that Sandy put in the `hod/` directory, but currently it isn't well-documented and its place is probably in `analysis/`. I am happy to put some comments for that and move it to `analysis` if you think that makes sense.

Ok, I agree with you that perhaps a numba dict would work better, but I couldn't make the syntax happy. Do you think you could help with that?

To your other point, I personally quite like the `N_k, N_poles` format as most of the time we are using at least `ell = 0` and `ell = 2`, so that makes intuitive sense to me.

2023-11-13 00:19 UTC, lgarrison commented
Not sure I follow about taking a file name; the current implementation doesn't take any less memory than reading the array from the file then calling the function with that array. I realize that the function is deleting the variable, but that's after the peak memory usage, which happens during the irfft. (nmesh=1152 sounds pretty small by the way; a single mesh of that size should take 6 GB, and the Perlmutter analysis nodes have 512 GB of RAM, so I'd expect you to be able to go much bigger, even if using many meshes.)

With regards to `shear.py`, that's fine if you want to move it to analysis. If applicable, we should document that the interface is unfinished/subject to change. (We should eventually try to define a proper public API for all of abacusutils so people know what they can code against, but for now we should at least warn people about work in progress.)

I'll probably tweak the power spectrum columns to have shape `(N_k,)` (i.e. squeeze the last axis) if only 1 pole is requested, that's probably a little more intuitive especially if one is only expecting the monopole.

I'll see if I can get the Numba dicts to work.

2023-11-13 03:47 UTC, boryanah commented
I don't know why, but I tested this, I thought quite robustly, before and found that it would run out of memory unless I do this loading and then deletion (this was capping at 100 GB and I was loading several other arrays, indeed). Could we perhaps leave it as an option to just pass a filename rather than an array if the input is a string?

Yes, that makes sense -- we can indicate it's work in progress.

Sure, though right now the output for `N_mu = 1` which is the most useful case is also a bit weird (I need to flatten that array to use as normal). Maybe that's what you mean.

Thanks, re: dicts.

2023-11-13 17:41 UTC, lgarrison commented
@boryanah Can you take a look at my recent changes? I modified `calc_pk_from_deltak` to return a dict, rather than modifying `bin_kmu` to avoid problems with Numba typed dicts. And `bin_kmu` is only used internally by this module, so it's okay if we have some rigidity in the return value ordering there. I also updated the names of the return values to align with `calc_power`; hopefully they're a little more intuitive now.

I updated the other parts of the code that use `calc_pk_from_deltak`, and the tests still pass, but I'm not sure how much test coverage those parts of the code have, so please take a look.

I will say now that we're returning a dict, the ZCV code is basically just renaming the keys to store in another dict. To me, this suggests that we should possibly be organizing the data in a different way; e.g. nested dicts, rather than flat dicts with renaming schemes. Just something to think about.

With regards to `pk_to_xi`, if you want to keep an option to read from a file, that's okay, but it does indicate something weird is going on that would be worth looking into.

2023-11-15 08:00 UTC, boryanah commented
Looks perfect! I was trying something very similar for the dictionary, but it didn't seem to like my syntax -- thank you.

2023-11-15 08:21 UTC, boryanah commented
Looking at the code, I agree: the `pk_to_xi` stuff is weird --  I wonder if it was an issue with the previous version of `bin_kmu`, which is called in the same function, in which I was creating the copies of the 3D k-array and mu-arrays. I was doing that until very recently (as I was also using the old version for a while). That must be it... I will get rid of the option of opening the file name, since it is more elegant that way (and we don't need to call `asdf` in the `power_spectrum` module).

Are you suggesting something like this: the ZCV module uses a mother dictionary that has the tracer, matter power spectrum and whatever else it needs and each of the daughters follows the same power spectrum format? Possibly, though I am not sure whether that would be that elegant given that the theory ZA predictions come in a pretty different format (since there are lots of terms we are not including). Though I agree that `tools_cv.py` is still a bit messy despite my attempts at revising it.

I will add that `shear.py` is under construction.

2023-11-15 08:39 UTC, boryanah commented
On my end, I think this is ready to push out.

2023-11-15 15:19 UTC, lgarrison commented
That makes a lot of sense about the old version of `bin_kmu`. For the ZCV dicts, `pk_ij_dict['P_kmu_delta_delta']` could be represented with nested dicts as `pk_ij_dict['delta']['delta']['kmu']['power']`, where the most deeply nested dict is just the dictionary as returned by `calc_pk_from_deltak`. It also avoids ugly key string construction. I'm not _really_ sure it's better---it probably depends on the downstream usage---but it's worth thinking about.

(To get the Pk dictionary to work you might have noticed I just removed the Numba annotation from `calc_pk_from_deltak`, it wasn't really doing anything. The only array manipulations were on binned power spectra, which are small.)

2023-11-15 16:01 UTC, merged