first pull request for AbacusHOD
abacusorg/abacusutils pull request #4
Opened 2021-01-26 20:57 UTC by SandyYuan

Implemented AbacusHOD.

2021-01-27 01:46 UTC, lgarrison requested changes
Just did a quick scan of the files; looks good.  The only big things are to move any scripts into a `abacusutils/scripts/hod` directory, and to add a basic test.  You can follow the example in `tests/test_data.py` or `tests/test_pipe_asdf.sh`; make a `test_hod.py/sh`, and just make a basic example that runs a single HOD evaluation and checks the likelihood or 2PCF, for example.  There's a tiny sim in the test directory that hopefully you can run on.

If getting a real test in place is too complicated right now, then a simple import test will do.  Either way, run `pytest` from the `abacusutils` dir to run the tests and check that they pass.

Also, don't forget to remove that `._abacus_hod.yaml` file.

2021-01-27 01:46 UTC, lgarrison commented on abacusnbody/hod/load_sims.py
> +import os
This is an example/testing script for the user to run, right? Should probably go in `abacusutils/scripts/hod`, along with other user-facing scripts that don't need to be importable.

Or, if there are parts that need to be importable and parts that a user runs directly, can use a setuptools "entry point" (see `pipe_asdf` example)

2021-02-02 16:23 UTC, SandyYuan commented on abacusnbody/hod/AbacusHOD/GRAND_HOD.py
> +
future item

2021-02-02 16:24 UTC, SandyYuan commented on abacusnbody/hod/AbacusHOD/GRAND_HOD.py
> +    qso_id = np.empty(N_qso, dtype = ids.dtype)
there was a reason when I was coding it, but I forgot. Does it matter?

2021-02-02 16:25 UTC, SandyYuan commented on abacusnbody/hod/AbacusHOD/abacus_hod.py
> +                * ``Nthread_load``: int, how many threads to use to load the simulation data, default 7.
future item. currently it is user set.

2021-02-02 16:40 UTC, lgarrison commented on abacusnbody/hod/AbacusHOD/GRAND_HOD.py
> +    qso_id = np.empty(N_qso, dtype = ids.dtype)
Not in terms of performance, just in terms of readability and maintainability.  e.g. It's easy to have bugs in the copy-paste.  In fact, I just spotted one, lin 229 has `N_lrg` instead of `N_qso`

2021-02-02 18:33 UTC, lgarrison requested changes
Can you remove all the "dotfiles" (`.DS_store`, etc)?  And move `CHANGES.rst` back to the repo root and restore the symlink in `docs/CHANGES.rst`?  You can go ahead and make a version 0.4.0 section and add an entry for the HOD code.

There's a `tests/tests` directory, is that a mistake?  The `tests` dir is getting a little crowded, can you make a `hod` directory and put all the outputs in there?  "Prepared" inputs can probably go in there too; the tests themselves can remain at the top level.  I'll do the same for the `data` tests.

2021-02-02 18:33 UTC, lgarrison commented on abacusnbody/hod/tpcf_corrfunc.py
> +    DD_counts_new = np.array([np.sum(DD_counts[i:i+pi_bin_size]) for i in range(0, len(DD_counts), pi_bin_size)])
So `pi_bin_size` needs to be an integer >= 1, right? And needs to divide pimax evenly, or else the last bin will have the wrong xi?  Are these conditions enforced anywhere?

2021-02-02 18:33 UTC, lgarrison commented on scripts/hod/config/abacus_hod.yaml
> +    Nthread_load: 7                                                          # number of thread for organizing simulation outputs (load_sims)
"prepare_sims", right?

2021-02-02 18:33 UTC, lgarrison commented on scripts/hod/config/abacus_hod.yaml
> +            path2cov: '/mnt/marvin1/syuan/scratch/targets_xi/data_xi_cov_mock_div8.npz'
Are these data against which the 2PCF is going to be fit in the MCMC? Is the format of the npz files documented?

Also, just a personal preference, I would probably write or `power_path` or `power_file`.

2021-02-02 18:33 UTC, lgarrison commented on scripts/hod/run_emcee.py
> +        from schwimmbad import MPIPool
another dependency?

2021-02-02 18:33 UTC, lgarrison commented on tests/LRGs.dat
> +# %ECSV 0.9
Can you rename this file to `LRGs.csv` or `LRGs.ecsv`?

2021-02-02 18:33 UTC, lgarrison commented on tests/run_hod.py
> +This is a script for generating HOD mock catalogs.
This is the script to run to do a new "preparation" of the test sim, right?  I think this ought to be done as part of the test, but if that's hard for some reason, then at least make a note in the docstring here that this is the script to re-run if the preparation stage needs to be updated.

2021-02-02 18:50 UTC, SandyYuan commented on abacusnbody/hod/GRAND_HOD.py
> +    if M_h - kappa*M_cut < 0:
It doesn't seem to affect performance. I guess njit is keeping it fast. I was thinking this might actually improve performance since it skips a lot of computes.

2021-02-02 18:51 UTC, SandyYuan commented on abacusnbody/hod/GRAND_HOD.py
> +    LRG_dict['id'] = lrg_id.astype(np.float64)
I think it is a "nice to have." This gives people a way to associate galaxies with host halos efficiently. But it is not required in anything right now.

2021-02-02 19:00 UTC, SandyYuan commented on abacusnbody/hod/abacus_hod.py
> +        Nparts_tot = np.sum(Nparts)
so you are saying just save a meta varialbe Nhalo in the h5 file? Right now I have to open the file, and access the length of an array, which is slower.

2021-02-02 19:07 UTC, SandyYuan commented on abacusnbody/hod/prepare_sim.py
> +    D, edges = np.histogramdd(halos['x_L2com'], weights = halos['N'],
TBD

2021-02-02 19:14 UTC, SandyYuan commented on abacusnbody/hod/prepare_sim.py
> +    for j in np.arange(len(halos)):
this is definitely the slowest part of prepare_sim. Do you have tricks in mind?

2021-02-02 19:23 UTC, SandyYuan commented on abacusnbody/hod/prepare_sim.py
> +        MT = True
Yes, it's kind of a misnomer. Currently, it is just differentiating between two states: LRG only, or else. So "ELG only" would also be considered multi-tracer.

2021-02-02 19:24 UTC, SandyYuan commented on abacusnbody/hod/tpcf_corrfunc.py
> +    DD_counts_new = np.array([np.sum(DD_counts[i:i+pi_bin_size]) for i in range(0, len(DD_counts), pi_bin_size)])
Not yet, should I do some "if, raiseError()"?

2021-02-02 19:28 UTC, SandyYuan commented on scripts/hod/config/abacus_hod.yaml
> +            path2cov: '/mnt/marvin1/syuan/scratch/targets_xi/data_xi_cov_mock_div8.npz'
Yeah, this is needed for the MC runs, and I havent looked at this code yet, since it is more like a use case. Do you think it is a priority to clean this up right now?

2021-02-02 19:30 UTC, SandyYuan commented on tests/run_hod.py
> +This is a script for generating HOD mock catalogs.
oh I actually meant to remove this file. Do you think we should keep it?

2021-02-02 19:43 UTC, lgarrison commented on abacusnbody/hod/abacus_hod.py
> +        Nparts_tot = np.sum(Nparts)
In theory, opening the file and just getting the length should be fast, as it doesn't have to read the actual data, just the metadata.  But if you tried that and it's still slow, then this is fine too.

2021-02-02 19:54 UTC, lgarrison commented on abacusnbody/hod/GRAND_HOD.py
> +    LRG_dict['id'] = lrg_id.astype(np.float64)
Okay. I know it's a bit messy, but I think I'd make a 4th dict, "id_dict", that has (up to) three keys: 'LRG', 'QSO', and 'ELG'. And the dict values are the integer ID arrays.  Casting isn't free, and floating-point IDs will be greatly confusing to end users!

2021-02-02 19:55 UTC, lgarrison commented on abacusnbody/hod/prepare_sim.py
> +    for j in np.arange(len(halos)):
Well, the only thing I was wondering was whether this could be implemented in numba.  It's hard to tell; the loop body is pretty big, but lots of it is simple math; maybe the conversion wouldn't be too tough.  Maybe for another day.

2021-02-02 20:00 UTC, lgarrison commented on abacusnbody/hod/prepare_sim.py
> +        MT = True
Gotcha, is MT an internal concept, or is that exposed to the user?  Should definitely document that if it's user-facing.

For the developers, maybe just drop an explanatory comment here.  If you're feeling motivated, this is the kind of thing that could go in a "Developer Documentation" section on the readthedocs.

2021-02-02 20:01 UTC, lgarrison commented on abacusnbody/hod/tpcf_corrfunc.py
> +    DD_counts_new = np.array([np.sum(DD_counts[i:i+pi_bin_size]) for i in range(0, len(DD_counts), pi_bin_size)])
Yeah, `raise ValueError(...)`

2021-02-02 20:03 UTC, lgarrison commented on scripts/hod/config/abacus_hod.yaml
> +            path2cov: '/mnt/marvin1/syuan/scratch/targets_xi/data_xi_cov_mock_div8.npz'
Wouldn't say a priority; maybe just a comment in the YAML is needed so users don't wonder what they're supposed to do with that section.

2021-02-02 20:05 UTC, lgarrison commented on tests/run_hod.py
> +This is a script for generating HOD mock catalogs.
If this is the script that needs to be re-run if the preparation data model changes, then this 100% needs to be here.  Or an equivalent shell script that calls `python -m abacusnbody.hod.prepare_sims Mini...`.  What do you think about making it part of the test?

2021-02-02 20:25 UTC, SandyYuan commented on abacusnbody/hod/GRAND_HOD.py
> +    for tid in numba.prange(Nthread):
Just tested, doesn't look like it.

2021-02-02 20:26 UTC, SandyYuan commented on abacusnbody/hod/prepare_sim.py
> +        MT = True
It is internal.

2021-02-02 20:54 UTC, SandyYuan commented on abacusnbody/hod/abacus_hod.py
> +        Nparts_tot = np.sum(Nparts)
Yep, just made this change.

2021-02-03 19:05 UTC, lgarrison approved these changes

2021-02-03 19:05 UTC, merged